parse_config:
  zmk_preamble: "#include <zmk-helpers/key-labels/34.h>"
  zmk_additional_includes:
    - "modules/helpers/include"
  raw_binding_map:
    '&sys_reset': Reset
    '&bootloader': Boot
    '&swapper': Win Next
    '&caps_word': Caps Word
    '&inv_qm': ¿

    '&kp LC(LG(LEFT))': Desk Left
    '&kp LC(LG(RIGHT))': Desk Right
    '&kp LC(TAB)': Tab Right
    '&kp LC(LS(TAB))': Tab Left
    '&kp LA(F4)': Win Close
    '&kp LC(F4)': Tab Close
    '&kp LS(TAB)': Win Prev
    '&kp LS(INS)': Paste
    '&kp LG(L)': Lock

    '&out OUT_USB': Out USB
    '&out OUT_BLE': Out BLE

    '&bt BT_SEL 0': BT 1
    '&bt BT_SEL 1': BT 2
    '&bt BT_SEL 2': BT 3
    '&bt BT_SEL 3': BT 4
    '&bt BT_SEL 4': BT 5

    '&mmv MOVE_UP': Mouse ↑
    '&mmv MOVE_DOWN': Mouse ↓
    '&mmv MOVE_LEFT': Mouse ←
    '&mmv MOVE_RIGHT': Mouse →

    '&msc SCRL_UP': Scroll ↑
    '&msc SCRL_DOWN': Scroll ↓
    '&msc SCRL_LEFT': Scroll ←
    '&msc SCRL_RIGHT': Scroll →

    '&mkp LCLK': Left Click
    '&mkp RCLK': Right Click
    '&mkp MCLK': Middle Click
    '&mkp MB4': Back Click
    '&mkp MB5': Forward Click

  zmk_keycode_map:
    # custom mappings
    C_VOL_UP: Vol Up
    C_VOL_DN: Vol Down
    C_AL_CALC: Calc
    C_PP: Play Pause
    K_MUTE: $$mdi:volume-mute$$

    LCTRL: Ctrl
    RCTRL: Ctrl
    LALT: Alt
    RALT: Alt
    LGUI: GUI
    RGUI: GUI
    LSHFT: Shift
    RSHFT: Shift
    # LSHFT: ⇧
    # RSHFT: ⇧
    ESC: Esc
    SPACE: ␣
    BSPC: ⌫
    # RET: ⏎
    RET: ⮐
    TAB: ↹
    DEL: ⌦

    PG_UP: Page Up
    PG_DN: Page Down
    INS: Insert
    HOME: Home
    END: End
    CAPS: Caps Lock
    PSCRN: Print Scrn
    PAUSE_BREAK: Pause Break

    UP: ↑
    DOWN: ↓
    LEFT: ←
    RIGHT: →

    C_PP: ⏯
    C_NEXT: ⏭️
    C_PREV: ⏮️

    # defaults
    AMPERSAND: '&'
    AMPS: '&'
    APOS: "'"
    APOSTROPHE: "'"
    ASTERISK: '*'
    ASTRK: '*'
    AT: '@'
    AT_SIGN: '@'
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ':'
    COMMA: ','
    DLLR: $
    DOLLAR: $
    DOT: .
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EQUAL: '='
    EXCL: '!'
    EXCLAMATION: '!'
    FSLH: /
    GRAVE: '`'
    GREATER_THAN: '>'
    GT: '>'
    HASH: '#'
    LBKT: '['
    LBRC: '{'
    LEFT_BRACE: '{'
    LEFT_BRACKET: '['
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: '-'
    NON_US_BACKSLASH: \
    NON_US_BSLH: '|'
    NON_US_HASH: '#'
    NUHS: '#'
    PERCENT: '%'
    PERIOD: .
    PIPE: '|'
    PIPE2: '|'
    PLUS: +
    POUND: '#'
    PRCNT: '%'
    QMARK: '?'
    QUESTION: '?'
    RBKT: ']'
    RBRC: '}'
    RIGHT_BRACE: '}'
    RIGHT_BRACKET: ']'
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMI: ;
    SEMICOLON: ;
    SINGLE_QUOTE: ''''
    SLASH: /
    SQT: ''''
    STAR: '*'
    TILDE: '~'
    TILDE2: '~'
    UNDER: _
    UNDERSCORE: _

draw_config:
  footer_text: "albertonoys/zmk-workspace"
  separate_combo_diagrams: true
  small_pad: 4.0
  legend_rel_y: -4.0
  glyph_tap_size: 24
  glyph_hold_size: 12
  glyph_shifted_size: 10
  combo_w: 26
  combo_h: 24
  svg_extra_style: 'svg.keymap{font-size: 17px;}'
  shrink_wide_legends: 4
